# --- 경로 설정 ---
base_dir: 'W:\'  # (deprecated) 작업 디렉토리, 기본값의 루트 디렉토리로 사용됩니다
comfui_dir: 'W:\ComfyUI_windows_portable\ComfyUI'  # ComfyUI 설치 디렉토리 (get_comfui_dir)
data_dir: 'W:\ComfyU-auto-script_data'     # 데이터 디렉토리 (get_data_dir)

# --- 처리할 타입 리스트 ---
types:
  - IL
  # - Pony

# --- char.yml 관련 설정 ---
char:
  # 제거할 태그 목록
  # 정규식 패턴 사용 가능: "/pattern/" 형태로 감싸면 정규식으로 인식됩니다.
  excluded_tags:
    - '/cum .*/'
    - '/from .*/'
    - '/mole .*/'
    - '/huge_breasts .*/'
    - '/holding .*/'
    - '/.*headphones.*/'
    - '/.*bandaid .*/'
    - '/.*censor.*/'
    - '/.*hands up.*/'
    - '/.*armor.*/'
    - '/.*epaulettes.*/'
    - '/.*megaphone.*/'
    - '/.*blindfold.*/'
    - '/.*hood.*/'
    - '/.*goggles.*/'
    - '/.*crossed arms.*/'
    - '/.*umbrella.*/'
    - '/.* body/'
    - '/.* lights/'
    - '/.* penis/'
    - '/.* focus/'
    - '/.* armor/'
    - '/.* horns/'
    - '/.* cum/'
    - '/.* hands together/'
    - '/.* hands clasped/'
    - '/.* mouth/'
    - '/.* background/'
    - 'looking at viewer'
    - '2boys'
    - 'crying'
    - 'censored'
    - 'covered face'
    - 'close-up'
    - 'weapon'
    - 'eyes closed'
    - 'character name'
    - 'copyright name'
    - 'card parody'
    - 'sun symbol'
    - 'gem (symbol)'
    - 'star (symbol)'
    - 'card (medium)'
    - 'monochrome'
    - 'arms up'
    - 'comic'
    - 'lying'
    - ':o'
    - 'head out of frame'
    - 'horns'
    - 'bodysuit'
    - 'anime screencap'
    - 'pale skin'
    - 'standing'
    - ':d'
    - 'spread legs'
    - 'blush'
    - 'night'
    - 'doggystyle'
    - 'clitoris'
    - 'sword'
    - 'kneeling'
    - 'cowboy shot'
    - 'blurry'
    - 'armor'
    - 'anime coloring'
    - 'hand up'
    - 'indoors'
    - 'standing'
    - '1boy'
    - 'ass'
    - 'nipples'
    - 'outdoors'
    - 'hetero'
    - 'cum'
    - 'ahoge'
    - 'sitting'
    - 'one eye closed'
    - 'breasts out'
    - 'mole'
    - 'mosaic censoring'
    - 'smile'
    - 'vaginal'
    - 'penis'
    - 'eyepatch'
    - 'pussy'
    - 'tongue'
    - 'sex'
    - 'closed eyes'
    - 'solo'
    - 'tongue out'
    - 'sky'
    - 'flower'
    - 'multiple girls'
    - 'microphone'
    - 'singing'
    - 'cup'
    - 'cloud'
    - 'music'
    - 'tree'
    - 'pov'
    - 'solo focus'
    - '/.*nude.*/'
    - 'arm grab'
  
  # dress 필드로 이동할 태그 목록
  # 정규식 패턴 사용 가능: "/pattern/" 형태로 감싸면 정규식으로 인식됩니다.
  dress_tags:
    - 'zettai ryouiki'
    - 'hat'
    - 'side slit'
    - 'top'
    - '/.* top.*/'
    - '/.* coat.*/'
    - '/.* footwear.*/'
    - '/.* bikini.*/'
    - '/.* costume.*/'
    - '/.* headwear.*/'
    - '/.* pantyhose.*/'
    - '/.* eyewear.*/'
    - '/.* shoulder.*/'
    - '/.* boots.*/'
    - '/.* hat.*/'
    - '/.* socks.*/'
    - '/.* clothes.*/'
    - '/.* sweater.*/'
    - '/.* cap.*/'
    - '/.*eyewear.*/'
    - '/.*navel.*/'
    - '/.*earrings.*/'
    - '/.*earrings.*/'
    - '/.*collarbone.*/'
    - '/.*sleeves.*/'
    - '/.*jewelry.*/'
    - '/.*greyscale.*/'
    - '/.*swimsuit.*/'
    - '/.*manga.*/'
    - '/.*shorts.*/'
    - '/.*swimsuit.*/'
    - '/.*thighhighs.*/'
    - '/.*underwear.*/'
    - '/.*jacket.*/'
    - '/.*nurse.*/'
    - '/.*footwear.*/'
    - '/.*gloves.*/'
    - '/.*frills.*/'
    - '/.*boot.*/'
    - '/.*choker.*/'
    - '/.*sweater.*/'
    - '/.*legwear.*/'
    - '/.*heels.*/'
    - '/.*sleeveless.*/'
    - '/.*thigh.*/'
    - '/.*belt.*/'
    - '/.*necklace.*/'
    - '/.*dress.*/'
    - '/.*skirt.*/'
    - '/.*shoulders.*/'
    - '/.*piercing.*/'
    - '/.*shirt.*/'
    - '/.*uniform.*/'
    - '/.*clothing.*/'
    - '/.*outfit.*/'
    - '/.*top-down bottom-up.*/'
    - '/.*panties.*/'
    - '/.* cleavage.*/'
    - '/.* jacket.*/'

# --- lora.yml 관련 설정 ---
lora:
  # 태그 최대 개수 제한
  max_tags: 64
  
  # 제거할 태그 목록
  # 정규식 패턴 사용 가능: "/pattern/" 형태로 감싸면 정규식으로 인식됩니다.
  excluded_tags:
    - '/.* eyes/'
    - '/.* background/'
    - '/.*blindfold.*/'
    - '/.*epaulettes.*/'
    - '/.*headphones.*/'
    - '/.*armor.*/'
    - '/.*handbag.*/'
    - '/.*bandaid .*/'
    - '/.*hood.*/'
    - '/.*censor.*/'
    - '/.*nude.*/'
    - 'looking at viewer'
    - 'monochrome'
    - 'covered face'
    - 'hyper realism'
    - 'identity censor'
    - 'top-down bottom-up'
    - 'censored'
    - 'eyepatch'
    - 'feet'
    - 'legs'
    - 'head out of frame'
    - 'realistic'
    - 'smile'
    - 'eyes closed'
    - 'solo'
    - 'bodysuit'
    - '1girl'
    - '1 girl'

# --- tag 관련 설정 ---
tag:
  # 태그 최대 개수 제한
  max_tags: 64
  
  # 제거할 태그 목록
  # 정규식 패턴 사용 가능: "/pattern/" 형태로 감싸면 정규식으로 인식됩니다.
  excluded_tags:
    - 'identity censor'
    - 'bandaid '
    - 'solo'
    - 'covered face'
    - '/.*armor.*/'
    - '/.*headphones.*/'
    - '1girl'
    - '1 girl'
    - 'censored'
    - 'hood'

